### ISSUE TITLE
api not downloading upto date nightly

### ISSUE THREAD

**Issue by dhlee49** [AdoptOpenJDK/openjdk-api-v3#121] opened 2020-03-06 22:36 UTC
### Problem Description
Currently I am running daily java tests around 1:40 am by pulling latest builds.
from February 26th, I see 5 ppc64le_openj9 builds from adoptopenjdk (https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9) for following dates -  6,10,23,25,26
however when I use the adoptapi to get latest build with following command, 

```
curl -OLJSks  https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/ppc64le/jdk/openj9/normal/adoptopenjdk
```
I got following jdk, which is pretty outdated
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+1-202002062012)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-f09513cd4, JRE 11 Linux ppc64le-64-Bit Compressed References 20200206_445 (JIT enabled, AOT enabled)
OpenJ9   - f09513cd4
OMR      - 001677f30
JCL      - 058070839f based on jdk-11.0.7+1)
```
if it doesn't pull the 25th build right next day its understandable but 0210 and 0221 builds should be there at least not the 0206 build

**Comment by johnoliver** [comment] 2020-03-07 11:13
when I run 
```
curl -vvv  https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/ppc64le/jdk/openj9/normal/adoptopenjdk
```
it shows me as being redirected to:

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-03-06-09-43/OpenJDK11U-jdk_ppc64le_linux_openj9_2020-03-06-09-43.tar.gz

At time of writing jdk11u-2020-03-06-09-43 is the most recent nightly release so it seems to me to be working as expected. Can you give me the checksum of what you are/have downloaded?

**Comment by dhlee49** [comment] 2020-03-16 19:09
i tried to find if downloaded files are still there but it got wiped out by our automation process- this happens once in a while where api won't update for few days when there are builds out not too sure if I can reproduce this unless i spot it while it happens

**Comment by johnoliver** [comment] 2020-03-24 12:27
@dhlee49 there have had issues in the past with the api getting stuck while updating, we are put in the appropriate health checks to make sure that does not happen, but is probably caused by that.

**Comment by karianna** [comment] 2020-03-24 14:24
health check has landed.

**Closed by karianna** 2020-03-24 14:24 UTC
Labels: bug
