### ISSUE TITLE
Add Dragonwell in openjdk-api/v3/binary

### ISSUE THREAD

**Issue by joeyleeeeeee97** [AdoptOpenJDK/openjdk-api-v3#375] opened 2021-03-18 09:29 UTC
Could we place it under openjdk?

**Comment by aahlenst** [comment] 2021-03-18 12:39
Dupe of #369?

**Comment by joeyleeeeeee97** [comment] 2021-03-19 06:38
@aahlenst Yes.. please close it.

**Closed** 2021-03-19 06:39 UTC
Labels: enhancement
